let obj = [
  {
    //   YASH
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Television",
      "Functional Kitchen",
    ],
    bathroom: "3",
    bedroom: "2",
    city: "goa",
    costpernight: "2000",
    country: "India",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/86680834/3b6fe44dcdf311e89ed80a8e1b1ce4da_watermarked_image_1024.jpeg",
    maxguests: "5",
    refid: "123",
    title: "Supreme Ac Stay At Resort In Calangute",
    type_of_property: "Serviced Apartment",
  },

  {
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Housekeeping",
      "Functional Kitchen",
      "Washing Machine",
      "Dish Washer",
    ],
    bathroom: "4",
    bedroom: "4",
    city: "goa",
    costpernight: "20000",
    country: "India",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/29525985/85be9537001f11e890160a8e1b1ce4da_watermarked_image_1024.jpeg",
    maxguests: "12",
    refid: "",
    title: "Luxury Villa With Private Swimming Pool",
    type_of_property: "Villa",
  },

  {
    Ammenities: ["Internet", "Parking", "Refrigerator"],
    bathroom: "1",
    bedroom: "1",
    city: "goa",
    costpernight: "4000",
    country: "India",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/20098241/a_watermarked_image_1024.jpeg",
    maxguests: "4",
    refid: "456",
    title: "",
    type_of_property: "Homestay",
  },

  {
    Ammenities: [
      "Air Conditioner",
      "Internet",
      "Television",
      "Parking",
      "Functional Kitchen",
      "Refrigerator",
      "Spa",
      "Cook On",
    ],
    bathroom: "2",
    bedroom: "2",
    city: "goa",
    costpernight: "8000",
    country: "India",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/20527902/97d7cc23217311eaa3940a5f3ca25ae5_watermarked_image_1024.jpeg",
    maxguests: "4",
    refid: "791",
    title: "2 Bedroom Ac Villa",
    type_of_property: "Villa",
  },

  {
    Ammenities: [
      "Air Conditioner",
      "Internet",
      "Parking",
      "Housekeeping",
      "Functional Kitchen",
      "Dish Washer",
      "Refrigerator",
      "Gym",
      "Spa",
    ],
    bathroom: "3",
    bedroom: "3",
    city: "goa",
    costpernight: "7000",
    country: "India",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/87931650/f20734fbf23b11e888730a8e1b1ce4da_watermarked_image_1024.jpeg",
    maxguests: "8",
    refid: "654",
    title: "3 Bedroom Bungalow At Villa Venus In Candolim, Goa",
    type_of_property: "Villa",
  },

  {
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Television",
      "Functional Kitchen",
    ],
    bathroom: "2",
    bedroom: "2",
    city: "goa",
    costpernight: "5000",
    country: "India",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/25773982/0808dd53d37111e7ae4e0a8e1b1ce4da_watermarked_image_1024.jpeg",
    maxguests: "6",
    refid: "897",
    title: "2bhk Pool Facing Apartment.",
    type_of_property: "Villa",
  },
  //  Praful
  {
    city: "Galle",
    country: "Srilanka",
    title: "Mango House",
    img_url:
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/230558363.jpg?k=d346be7aa296bc8772e2996141038c379a61a14281bf02293a19101306a85b6f&o=&hp=1",
    type_of_property: "Hotel",
    bedroom: 1,
    bathroom: 1,
    maxguests: 3,
    costpernight: 4000,
    refid: 101,
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Gym",
      "Spa",
      "Cook On ",
    ],
  },

  {
    city: "Galle",
    country: "Srilanka",
    title: "Brixia Cafe & Guest",
    img_url:
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/236972707.jpg?k=a66eef644757a0d86dde2895f836de6ceeb403b121e1fde27286b3ce5d679dc3&o=&hp=1",
    type_of_property: "Villa",
    bedroom: 1,
    bathroom: 1,
    maxguests: 3,
    costpernight: 800,
    refid: 201,
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Television",
      "Parking",
      "Housekeeping",
      "Functional Kitchen",
      "Washing Machine",
    ],
  },
  {
    city: "Galle",
    country: "Srilanka",
    title: "Le Grand Galle By Asia Leisure",
    img_url:
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/174997700.jpg?k=d14a49e71bbeff56a57429affe6eb1aa128053b6cb68c786d9ec6af48bdc3e03&o=&hp=1",
    type_of_property: "Resort",
    bedroom: 1,
    bathroom: 1,
    maxguests: 3,
    costpernight: 1000,
    refid: 301,
    Ammenities: ["Swimming Pool", "Air Conditioner", "Internet"],
  },
  {
    city: "Galle",
    country: "Srilanka",
    title: "Radisson Blu Resort Galle",
    img_url:
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/114423094.jpg?k=82c2e7976d8c088d690c2688e76cdbc641e5db9df1b68a4d3f1c9af2f1ccbb68&o=&hp=1",
    type_of_property: "Hotel",
    bedroom: 1,
    bathroom: 1,
    maxguests: 3,
    costpernight: 2100,
    refid: 401,
    Ammenities: [
      "Housekeeping",
      "Functional Kitchen",
      "Washing Machine",
      "Dish Washer",
      "Refrigerator",
      "Gym",
      "Spa",
      "Cook On ",
    ],
  },
  {
    city: "Galle",
    country: "Srilanka",
    title: "Secret Garden Galle FortOpens in new window",
    img_url:
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/224072302.jpg?k=93d83f0f79bb0e5e640a2e1a6b5b42a82c2e0d376f3cb9a284fe19047c59983d&o=&hp=1",
    type_of_property: "Homestay",
    bedroom: 1,
    bathroom: 1,
    maxguests: 3,
    costpernight: 3000,
    refid: 501,
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Television",
      "Parking",
      "Housekeeping",
      "Functional Kitchen",
      "Washing Machine",
      "Dish Washer",
      "Refrigerator",
      "Gym",
      "Spa",
      "Cook On ",
    ],
  },
  // Tarun

  {
    city: "Lonavala",
    country: "India",
    title: "Cozy 2 Bhk Villa In Lonavala With Lounge Pool",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/62908066/921a3775f5ed11eabc030a5f3ca25ae5_watermarked_image_1024.jpeg",
    type_of_property: "Villa",
    bedroom: "2",
    bathroom: "3",
    maxguests: "10",
    costpernight: "7875",
    refid: "129",
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Housekeeping",
      "Functional Kitchen",
      "Washing Machine",
    ],
  },

  {
    city: "Lonavala",
    country: "India",
    title: "Sublime Lonavala Weekend Rental Villa",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/10955990/bfd091ef7b6b11e8b1610a8e1b1ce4da_watermarked_image_1024.jpeg",
    type_of_property: "Villa",
    bedroom: "4",
    bathroom: "4",
    maxguests: "20",
    costpernight: "25000",
    refid: "155",
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Television",
      "Refrigerator",
      "Gym",
    ],
  },

  {
    city: "Lonavala",
    country: "India",
    title: "Marina Exotic Villa In Lonavala",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/16225285/img-20161104-wa0001_watermarked_image_1024.jpeg",
    type_of_property: "Apartment",
    bedroom: "4",
    bathroom: "5",
    maxguests: "16",
    costpernight: "25000",
    refid: "781",
    Ammenities: [
      "Swimming Pool",
      "Washing Machine",
      "Dish Washer",
      "Refrigerator",
      "Gym",
    ],
  },

  {
    city: "Lonavala",
    country: "India",
    title: "Modi House Lonavala ",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/81405910/b08c93cf935a11e99e4e0a8e1b1ce4da_watermarked_image_1024.jpeg",
    type_of_property: "Farm",
    bedroom: "4",
    bathroom: "6",
    maxguests: "16",
    costpernight: "23700",
    refid: "154",
    Ammenities: [
      "Air Conditioner",
      "Housekeeping",
      "Functional Kitchen",
      "Washing Machine",
      "Dish Washer",
      "Refrigerator",
    ],
  },

  {
    city: "Lonavala",
    country: "India",
    title: "Marina Grand Villa In Lonavala, Maharashtra ",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/28072663/ccedf6fa85c711ebbcb70a5f3ca25ae5_watermarked_image_1024.jpeg",
    type_of_property: "Villa",
    bedroom: "3",
    bathroom: "5",
    maxguests: "14",
    costpernight: "12000",
    refid: "552",
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Television",
      "Parking",
      "Functional Kitchen",
      "Washing Machine",
      "Cook On",
    ],
  },

  //Gokul

  {
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Television",
      "Parking",
      "Housekeeping",
      "Washing Machine",
      "Refrigerator",
      "Spa",
      "Cook On",
    ],
    bathroom: "4",
    bedroom: "5",
    city: "Pataya",
    costpernight: "10000",
    country: "Thailand",
    img_url:
      "https://www.tripvillas.com/holiday-home/31900325-jomtien-paradise-villa-5-bed-property-with-jet-pool-and-sauna-in-pattaya/",
    maxguests: "10",
    refid: "200",
    title:
      "Jomtien Paradise Villa | 5 Bed Property With Jet Pool And Sauna In Pattaya",
    type_of_property: "Villa",
    Rating: 4,
  },
  {
    Ammenities: ["Swimming Pool", "Air Conditioner", "Internet", "Television"],
    bathroom: "5",
    bedroom: "5",
    city: "Pataya",
    costpernight: "80000",
    country: "Thailand",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/46007896/0b5364faa2c711e783140a92a929817e_watermarked_image_1024.jpeg",

    maxguests: "10",
    refid: "201",
    title:
      "Baan Chokdee | 5 Bed Pool Villa Near Jomtien Beach In South Pattaya",
    type_of_property: "Villa",
    Rating: 5,
  },
  {
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Television",
      "Parking",
      "Spa",
    ],
    bathroom: "2",
    bedroom: "2",
    city: "Pataya",
    costpernight: "4000",
    country: "Thailand",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/36952294/7819757aa2c511e783140a92a929817e_watermarked_image_1024.jpeg",
    maxguests: "5",
    refid: "202",
    title:
      "Pratumnak Regal Villa | 2 Bed Pool Home At Pratumnak Hill In Pattaya",
    Rating: "3",
  },
  {
    Ammenities: ["Internet", "Television", "Parking"],
    bathroom: "1",
    bedroom: "2",
    city: "Pataya",
    costpernight: "3000",
    country: "Thailand",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/72289717/255_watermarked_image_1024.jpeg",
    maxguests: "4",
    refid: "203",
    title: "Boutique Resort For Rent - Pepper Villa (2 Bedrooms) Stay",
    type_of_property: "Farm",
    Rating: "5",
  },
  {
    Ammenities: [
      "Swimming Pool",
      "Air Conditioner",
      "Internet",
      "Parking",
      "Spa",
      "Cook On",
    ],
    bathroom: "2",
    bedroom: "3",
    city: "Pataya",
    costpernight: "5000",
    country: "Thailand",
    img_url:
      "https://d2vcelvjdj7n25.cloudfront.net/media/property_photos/image_watermarked_1024/32358195/82ededb7a2ca11e783180a92a929817e_watermarked_image_1024.jpeg",
    maxguests: "6",
    refid: "204",
    title: "Thammachat P3 Victoria | 3 Bedroom Pattaya Pool Villa In Bangsaray",
    type_of_property: "Farm",
    Rating: "4.5",
  },
];

let x = document.getElementById("goa1");
x.addEventListener("click", () => {
  console.log("HELLO");
  let ar = obj.filter((el) => {
    return el.city == "goa";
  });
  console.log(ar);
  localStorage.setItem("hotles_by_city", JSON.stringify(ar));
});
